# -*- coding: utf-8 -*-
"""ventana_evaluacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lB8JrJ4PGcPCOoHxrshmFW-onBGt_Wao
"""

from PyQt5.QtWidgets import QWidget, QLabel, QRadioButton, QPushButton, QVBoxLayout, QMessageBox, QButtonGroup
from ventana_resultados import VentanaResultados

class VentanaEvaluacion(QWidget):
    def __init__(self, nombre_usuario, modulo_seleccionado):
        super().__init__()
        self.usuario = nombre_usuario
        self.modulo = modulo_seleccionado

        self.indice_pregunta = 0
        self.respuestas_correctas = 0

        # --- BANCO DE PREGUNTAS AMPLIADO ---
        self.banco_preguntas = {
            "Seguridad e Higiene": [
                {"pregunta": "¿Qué color indica obligación en los carteles de seguridad?", "opciones": ["Azul", "Rojo", "Amarillo"], "correcta": "Azul"},
                {"pregunta": "¿Qué se debe hacer en caso de evacuación?", "opciones": ["Usar el ascensor", "Salir en orden por la salida de emergencia", "Correr"], "correcta": "Salir en orden por la salida de emergencia"}
            ],
            "Atención al Cliente": [
                {"pregunta": "¿Cuál es el primer paso al recibir una queja?", "opciones": ["Discutir con el cliente", "Escuchar activamente con empatía", "Ignorar el problema"], "correcta": "Escuchar activamente con empatía"},
                {"pregunta": "¿Qué significa una comunicación asertiva?", "opciones": ["Hablar fuerte", "Expresarse de forma clara y respetuosa", "Dar siempre la razón"], "correcta": "Expresarse de forma clara y respetuosa"}
            ],
            "Ciberseguridad": [
                {"pregunta": "¿Qué debes hacer si recibes un correo sospechoso pidiendo tu contraseña?", "opciones": ["Responderlo inmediatamente", "Reportarlo al área de TI y borrarlo", "Cambiar tu contraseña por la que te piden"], "correcta": "Reportarlo al área de TI y borrarlo"},
                {"pregunta": "¿Cuál es una práctica segura para el manejo de contraseñas corporativas?", "opciones": ["Anotarla en un post-it visible", "Usar la misma para todos los sistemas", "Usar contraseñas largas, complejas y únicas"], "correcta": "Usar contraseñas largas, complejas y únicas"}
            ],
            "Liderazgo": [
                {"pregunta": "¿Cuál es la principal característica de un líder democrático?", "opciones": ["Tomar decisiones sin consultar a nadie", "Fomentar la participación del equipo en las decisiones", "Delegar absolutamente todo sin supervisar"], "correcta": "Fomentar la participación del equipo en las decisiones"},
                {"pregunta": "Para motivar de forma efectiva a un equipo de trabajo se debe:", "opciones": ["Reconocer los logros y dar retroalimentación constructiva", "Señalar únicamente los errores en público", "Evitar la comunicación constante"], "correcta": "Reconocer los logros y dar retroalimentación constructiva"}
            ],
            "Protección de Datos": [
                {"pregunta": "¿Qué se considera un dato personal sensible bajo las normativas actuales?", "opciones": ["El nombre de la empresa", "Historial médico o convicciones religiosas", "La marca de la computadora asignada"], "correcta": "Historial médico o convicciones religiosas"},
                {"pregunta": "Si un cliente solicita eliminar sus datos de la base de datos corporativa, debes:", "opciones": ["Ignorar la solicitud", "Seguir el protocolo interno para el derecho de supresión/olvido", "Decirle que es imposible"], "correcta": "Seguir el protocolo interno para el derecho de supresión/olvido"}
            ]
        }

        self.preguntas_actuales = self.banco_preguntas[self.modulo]
        self.inicializar_ui()

    def inicializar_ui(self):
        self.setWindowTitle(f"Evaluación: {self.modulo}")
        self.setGeometry(100, 100, 550, 400)

        # --- ESTILO CSS (QSS) CON DEGRADADO ---
        self.setStyleSheet("""
            QWidget {
                background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #1b365d, stop:1 #4b779a);
                color: white;
                font-size: 16px;
            }
            QLabel {
                background: transparent;
            }
            QRadioButton {
                background: transparent;
                padding: 5px;
            }
            QRadioButton::indicator {
                width: 18px;
                height: 18px;
            }
            QPushButton {
                background-color: #2a9d8f;
                color: white;
                font-weight: bold;
                border-radius: 5px;
                padding: 10px;
                margin-top: 15px;
            }
            QPushButton:hover {
                background-color: #264653;
            }
        """)

        # Componentes
        self.etiqueta_saludo = QLabel(f"<b>Empleado:</b> {self.usuario}")
        self.etiqueta_pregunta = QLabel("")
        self.etiqueta_pregunta.setWordWrap(True) # Permite que la pregunta use varios renglones si es larga
        self.etiqueta_pregunta.setStyleSheet("font-size: 18px; font-weight: bold; margin-top: 10px; margin-bottom: 10px;")

        self.opcion1 = QRadioButton("")
        self.opcion2 = QRadioButton("")
        self.opcion3 = QRadioButton("")

        self.grupo_opciones = QButtonGroup()
        self.grupo_opciones.addButton(self.opcion1)
        self.grupo_opciones.addButton(self.opcion2)
        self.grupo_opciones.addButton(self.opcion3)

        self.boton_siguiente = QPushButton("Siguiente Pregunta")
        self.boton_siguiente.clicked.connect(self.procesar_respuesta)

        # Diseño
        diseno = QVBoxLayout()
        diseno.addWidget(self.etiqueta_saludo)
        diseno.addWidget(self.etiqueta_pregunta)
        diseno.addWidget(self.opcion1)
        diseno.addWidget(self.opcion2)
        diseno.addWidget(self.opcion3)
        diseno.addWidget(self.boton_siguiente)
        self.setLayout(diseno)

        self.cargar_pregunta()

    def cargar_pregunta(self):
        self.grupo_opciones.setExclusive(False)
        self.opcion1.setChecked(False)
        self.opcion2.setChecked(False)
        self.opcion3.setChecked(False)
        self.grupo_opciones.setExclusive(True)

        datos_pregunta = self.preguntas_actuales[self.indice_pregunta]
        self.etiqueta_pregunta.setText(f"Pregunta {self.indice_pregunta + 1}: {datos_pregunta['pregunta']}")
        self.opcion1.setText(datos_pregunta["opciones"][0])
        self.opcion2.setText(datos_pregunta["opciones"][1])
        self.opcion3.setText(datos_pregunta["opciones"][2])

    def procesar_respuesta(self):
        opcion_seleccionada = ""
        if self.opcion1.isChecked():
            opcion_seleccionada = self.opcion1.text()
        elif self.opcion2.isChecked():
            opcion_seleccionada = self.opcion2.text()
        elif self.opcion3.isChecked():
            opcion_seleccionada = self.opcion3.text()

        if opcion_seleccionada == "":
            QMessageBox.warning(self, "Advertencia", "Por favor, selecciona una respuesta.")
            return

        respuesta_correcta = self.preguntas_actuales[self.indice_pregunta]["correcta"]
        if opcion_seleccionada == respuesta_correcta:
            self.respuestas_correctas += 1

        self.indice_pregunta += 1
        if self.indice_pregunta < len(self.preguntas_actuales):
            self.cargar_pregunta()
        else:
            puntaje_final = (self.respuestas_correctas / len(self.preguntas_actuales)) * 100
            self.ventana_res = VentanaResultados(self.usuario, self.modulo, puntaje_final)
            self.ventana_res.show()
            self.close()