# -*- coding: utf-8 -*-
"""ventana_resultados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKEiKBApvpiUbK_93im2eHUcuTaK4hIS
"""

from PyQt5.QtWidgets import QWidget, QLabel, QPushButton, QVBoxLayout

class VentanaResultados(QWidget):
    def __init__(self, nombre_usuario, modulo_seleccionado, puntaje):
        super().__init__()
        self.usuario = nombre_usuario
        self.modulo = modulo_seleccionado
        self.puntaje = puntaje

        self.inicializar_ui()

    def inicializar_ui(self):
        self.setWindowTitle("Resultado de la Evaluación")
        self.setGeometry(100, 100, 450, 350)

        # --- ESTILO CSS (QSS) CON DEGRADADO ---
        self.setStyleSheet("""
            QWidget {
                background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #1b365d, stop:1 #4b779a);
                color: white;
                font-size: 16px;
            }
            QLabel {
                background: transparent;
            }
            QPushButton {
                background-color: #e76f51;
                color: white;
                font-weight: bold;
                border-radius: 5px;
                padding: 10px;
                margin-top: 20px;
            }
            QPushButton:hover {
                background-color: #d62828;
            }
        """)

        # Componentes de la interfaz
        self.etiqueta_titulo = QLabel("--- RESULTADO DE EVALUACIÓN ---")
        self.etiqueta_titulo.setStyleSheet("font-size: 20px; font-weight: bold; qproperty-alignment: 'AlignCenter';")

        self.etiqueta_info = QLabel(f"<b>Empleado:</b> {self.usuario}\n<b>Módulo:</b> {self.modulo}\n<b>Puntaje:</b> {self.puntaje}%")

        self.etiqueta_estado = QLabel("")
        self.etiqueta_estado.setStyleSheet("font-size: 18px; font-weight: bold;")

        self.etiqueta_comprobante = QLabel("")

        # Lógica de aprobación (nota >= 70%)
        if self.puntaje >= 70:
            self.etiqueta_estado.setText("ESTADO: ¡APROBADO!")
            self.etiqueta_estado.setStyleSheet("color: #2a9d8f; font-size: 18px; font-weight: bold;")
            self.etiqueta_comprobante.setText("COMPROBANTE GENERADO:\nCertificado de capacitación emitido con éxito.")
        else:
            self.etiqueta_estado.setText("ESTADO: REPROBADO")
            self.etiqueta_estado.setStyleSheet("color: #e63946; font-size: 18px; font-weight: bold;")
            self.etiqueta_comprobante.setText(f"Debes repasar el contenido del módulo:\n-> {self.modulo}")

        self.boton_cerrar_sesion = QPushButton("Cerrar Sesión")
        self.boton_cerrar_sesion.clicked.connect(self.volver_al_login)

        # Diseño
        diseno = QVBoxLayout()
        diseno.setSpacing(12)
        diseno.addWidget(self.etiqueta_titulo)
        diseno.addWidget(self.etiqueta_info)
        diseno.addWidget(self.etiqueta_estado)
        diseno.addWidget(self.etiqueta_comprobante)
        diseno.addWidget(self.boton_cerrar_sesion)
        self.setLayout(diseno)

    def volver_al_login(self):
        from ventana_login import VentanaLogin
        self.nueva_sesion = VentanaLogin()
        self.nueva_sesion.show()
        self.close()